title: SPOT 2019
description: > # this means to ignore newlines until "baseurl:"
  Cryptocurrency Exchanges Conference in Hong Kong, July 29
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.spotconf.com" # the base hostname & protocol for your site
image: "../css/2019_style/img/og.png"
author: Leonhard Weese
# Build settings
markdown: kramdown
lang: en_HK

# Social
logo: "../css/2019_style/img/icon-large.png"

twitter:
  username: bitcoinorghk
  card: summary

include: ['_2018_pages', '_2019_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bitcoinorghk
  - title: twitter
    url: https://twitter.com/bitcoinorghk
  - title: instagram
    url: https://www.instagram.com/bitcoinorghk/
  - title: linkedin
    url: https://www.linkedin.com/company/the-bitcoin-association-of-hong-kong/

# Build settings
markdown: kramdown
permalink: pretty
