title: SPOT 2019
description: > # this means to ignore newlines until "baseurl:"
  Cryptocurrency Exchanges Conference in Hong Kong
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.spotconf.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2019_style/img/icon-large.png"

social: 
  name: Bitcoin Association of Hong Kong
  link: "https://www.facebook.com/bitcoinorghk"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages', '_2019_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bitcoinorghk
  - title: twitter
    url: https://twitter.com/bitcoinorghk
  - title: instagram
    url: https://www.instagram.com/bitcoinorghk/
  - title: linkedin
    url: https://www.linkedin.com/company/the-bitcoin-association-of-hong-kong/

# Build settings
markdown: kramdown
permalink: pretty
